# Build a base go image.
FROM golang:1.19-alpine as builder

RUN mkdir /app

COPY . /app

WORKDIR /app

RUN CGO_ENABLED=0 go build -o authentication ./cmd/api

RUN chmod +x /app/authentication

# Build a tiny docker image.
FROM alpine:latest

RUN mkdir /app

COPY --from=builder /app/authentication /app

CMD ["/app/authentication"]